local ZGV = ZygorGuidesViewer
if not ZGV then return end

local GuideMenu = ZGV.GuideMenu

GuideMenu.HomeVersion = 1
GuideMenu.Home={
{"title", text=[[This Update:]]},
	{"banner", image=ZGV.DIR.."\\Skins\\banner"},
	{"section", text=[[EVENTS]]},
	{"item", text=[[Updated |cfffe6100Feast of Winter Veil Quests|r.]], guide="EVENTS\\Feast of Winter Veil\\Feast of Winter Veil Quests"},
	{"item", text=[[Updated |cfffe6100Feast of Winter Veil Dailies|r.]], guide="EVENTS\\Feast of Winter Veil\\Feast of Winter Veil Quests"},
	{"item", text=[[Updated |cfffe6100Feast of Winter Veil Achievements|r.]], guide="EVENTS\\Feast of Winter Veil\\Feast of Winter Veil Quests"},
	{"separator"},
	{"title", text=[[Recent Updates]]},
	{"section", text=[[LEVELING]]},
	{"item", text=[[Updated |cfffe6100Suramar Insurrection Week 8|r.]], guide="LEVELING\\Legion (100-110)\\Suramar (110)"},
	{"section", text=[[DUNGEONS]]},
	{"item", text=[[Added |cfffe6100Karazhan Attunment|r.]], guide="DUNGEONS\\Legion Dungeons\\Karazhan\\Karazhan Attunement"},
	{"item", text=[[Added |cfffe6100Return to Karazhan|r.]], folder="DUNGEONS\\Legion Dungeons\\Karazhan"},
	{"section", text=[[EVENTS]]},
	{"item", text=[[Updated |cfffe6100Pilgrim's Bounty|r.]], folder="EVENTS\\Pilgrim's Bounty"},
	{"section", text=[[PROFESSIONS]]},
	{"item", text=[[Added |cfffe6100Archaeology Quest Line|r.]], guide="PROFESSIONS\\Archaeology\\Legion\\Archaeology Quest Line"},
	{"item", text=[[Added |cfffe6100Archaeology 700-800|r.]], guide="PROFESSIONS\\Archaeology\\Legion\\Archaeology 700-800"},
	{"item", text=[[Added |cfffe6100Cooking Quest Line|r.]], guide="PROFESSIONS\\Cooking\\Legion\\Cooking Quest Line"},
	{"item", text=[[Added |cfffe6100Cooking 700-800|r.]], guide="PROFESSIONS\\Cooking\\Legion\\Cooking 700-800"},
	{"item", text=[[Added |cfffe6100Engineering Quest Line|r.]], guide="PROFESSIONS\\Engineering\\Legion\\Engineering Quest Line"},
	{"item", text=[[Added |cfffe6100Engineering 700-800|r.]], guide="PROFESSIONS\\Engineering\\Legion\\Engineering 700-800"},
	{"item", text=[[Added |cfffe6100First Aid Quest Line|r.]], guide="PROFESSIONS\\First Aid\\Legion\\First Aid Quest Line"},
	{"item", text=[[Added |cfffe6100First Aid 700-800|r.]], guide="PROFESSIONS\\First Aid\\Legion\\First Aid 700-800"},
	{"item", text=[[Added |cfffe6100Fishing Quest Line|r.]], guide="PROFESSIONS\\Fishing\\Legion\\Fishing Quest Line"},
	{"item", text=[[Added |cfffe6100Fishing 700-800|r.]], guide="PROFESSIONS\\Fishing\\Legion\\Fishing 700-800"},
	{"item", text=[[Added |cfffe6100Underlight Angler (Fishing Artifact)|r.]], guide="PROFESSIONS\\Fishing\\Legion\\Underlight Angler (Fishing Artifact)"},
	{"item", text=[[Added |cfffe6100Inscription Quest Line|r.]], guide="PROFESSIONS\\Inscription\\Legion\\Inscription Quest Line"},
	{"item", text=[[Added |cfffe6100Inscription 700-800|r.]], guide="PROFESSIONS\\Inscription\\Legion\\Inscription 700-800"},
	{"item", text=[[Added |cfffe6100Jewelcrafting Quest Line|r.]], guide="PROFESSIONS\\Jewelcrafting\\Legion\\Jewelcrafting Quest Line"},
	{"item", text=[[Added |cfffe6100Jewelcrafting 700-800|r.]], guide="PROFESSIONS\\Jewelcrafting\\Legion\\Jewelcrafting 700-800"},
	{"section", text=[[ACHIEVEMENTS]]},
	{"item", text=[[Added |cfffe6100A Cast Above The Rest|r.]], guide="ACHIEVEMENTS\\Professions\\Fishing\\A Cast Above the Rest"},
	{"item", text=[[Added |cfffe6100Bigger Fish to Fry|r.]], guide="ACHIEVEMENTS\\Professions\\Fishing\\Bigger Fish to Fry"},
	{"item", text=[[Added |cfffe6100Broken Isles Explorer|r.]], guide="ACHIEVEMENTS\\Exploration\\Legion\\Broken Isles Explorer"},
	{"item", text=[[Added |cfffe6100Loremaster of Legion|r.]], guide="ACHIEVEMENTS\\Quests\\Legion\\Loremaster of Legion"},
	{"item", text=[[Added |cfffe6100Variety is the Spice of Life|r.]], guide="ACHIEVEMENTS\\Quests\\Legion\\Variety is the Spice of Life"},
	{"item", text=[[Added |cfffe6100Broken Isles Diplomat|r.]], guide="ACHIEVEMENTS\\Reputation\\Legion\\Broken Isles Diplomat"},
	{"item", text=[[Added |cfffe6100A Glorious Campaign|r.]], guide="ACHIEVEMENTS\\Class Hall\\A Glorious Campaign"},
	{"item", text=[[Added |cfffe6100Broken Isles Pathfinder, Part One|r.]], guide="ACHIEVEMENTS\\Class Hall\\Broken Isles Pathfinder, Part One"},
	{"item", text=[[Added |cfffe6100Explore Azsuna|r.]], guide="ACHIEVEMENTS\\Exploration\\Legion\\Explore Azsuna"},
	{"item", text=[[Added |cfffe6100Explore Val'sharah|r.]], guide="ACHIEVEMENTS\\Exploration\\Legion\\Explore Val'sharah"},
	{"item", text=[[Added |cfffe6100Explore Highmountain|r.]], guide="ACHIEVEMENTS\\Exploration\\Legion\\Explore Highmountain"},
	{"item", text=[[Added |cfffe6100Explore Stormheim|r.]], guide="ACHIEVEMENTS\\Exploration\\Legion\\Explore Stormheim"},
	{"item", text=[[Added |cfffe6100Explore Suramar|r.]], guide="ACHIEVEMENTS\\Exploration\\Legion\\Explore Suramar"},
	{"section", text=[[REPUTATIONS]]},
	{"item", text=[[Added |cfffe6100Court of Farondis|r.]], guide="REPUTATIONS\\Legion\\Court of Farondis"},
	{"item", text=[[Added |cfffe6100Dreamweavers|r.]], guide="REPUTATIONS\\Legion\\Dreamweavers"},
	{"item", text=[[Added |cfffe6100Highmountain Tribe|r.]], guide="REPUTATIONS\\Legion\\Highmountain Tribe"},
	{"item", text=[[Added |cfffe6100Valarjar|r.]], guide="REPUTATIONS\\Legion\\Valarjar"},
	{"item", text=[[Added |cfffe6100The Nightfallen|r.]], guide="REPUTATIONS\\Legion\\The Nightfallen"},
	{"item", text=[[Added |cfffe6100Conjurer Margoss|r.]], guide="REPUTATIONS\\Legion\\Conjurer Margoss"},
	{"separator"},
}